export const types = {
    FETCH_EMPLOYEES_REQUEST: 'FETCH_EMPLOYEES_REQUEST',
    FETCH_EMPLOYEES_SUCCESS:'FETCH_EMPLOYEES_SUCCESS',
    FETCH_EMPLOYEES_FAILURE: 'FETCH_EMPLOYEES_FAILURE',

    GET_EMPLOYEE_REQUEST: 'GET_EMPLOYEE_REQUEST',
    GET_EMPLOYEE_SUCCESS: 'GET_EMPLOYEE_SUCCESS',
    GET_EMPLOYEE_FAILURE: 'GET_EMPLOYEE_FAILURE',

    SET_EMPLOYEE_REQUEST: 'SET_EMPLOYEE_REQUEST',
    SET_EMPLOYEE_SUCCESS: 'SET_EMPLOYEE_SUCCESS',
    SET_EMPLOYEE_FAILURE: 'SET_EMPLOYEE_FAILURE',

    PUT_EMPLOYEE_REQUEST: 'PUT_EMPLOYEE_REQUEST',
    PUT_EMPLOYEE_SUCCESS: 'PUT_EMPLOYEE_SUCCESS',
    PUT_EMPLOYEE_FAILURE: 'PUT_EMPLOYEE_FAILURE',

    POST_EMPLOYEE_REQUEST: 'POST_EMPLOYEE_REQUEST',
    POST_EMPLOYEE_SUCCESS: 'POST_EMPLOYEE_SUCCESS',
    POST_EMPLOYEE_FAILURE: 'POST_EMPLOYEE_FAILURE',

    DELETE_EMPLOYEE_REQUEST: 'DELETE_EMPLOYEE_REQUEST',
    DELETE_EMPLOYEE_SUCCESS: 'DELETE_EMPLOYEE_SUCCESS',
    DELETE_EMPLOYEE_FAILURE: 'DELETE_EMPLOYEE_FAILURE'
}