export const TYPES = {
    STATE_REQUEST: 'STATE_REQUEST',
    SET_USER_SUCCESS: 'SET_USER_SUCCESS',
    SET_USER_FAILURE: 'SET_USER_FAILURE',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    SET_REMEMBER_ME_SUCCESS: 'SET_REMEMBER_ME_SUCCESS',
    SET_REMEMBER_ME_FAILURE: 'SET_REMEMBER_ME_FAILURE',

    GET_REMEMBER_ME_SUCCESS: 'GET_REMEMBER_ME_SUCCESS',
    GET_REMEMBER_ME_FAILURE: 'GET_REMEMBER_ME_FAILURE',

    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE'
}