export const types = {
    CHANGE_LANGUAGE_SUCCESS: 'CHANGE_LANGUAGE_SUCCESS',
    CHANGE_LANGUAGE_FAILURE: 'CHANGE_LANGUAGE_FAILURE',

    ACTIVATE_LANG_MODAL_SUCCESS: 'ACTIVATE_LANG_MODAL_SUCCESS',
    ACTIVATE_LANG_MODAL_FAILURE: 'ACTIVATE_LANG_MODAL_FAILURE'
}