export const employeesData = [
    {
        id: 1,
        firstName: 'Fernando',
        lastName: '',
        jobTitle: 'Gte. Comercial',
        email: 'fernando@gmail.com',
        workPhone: '2652',
        homePhone: '',
        mobilePhone: '',
        country: 'Rep. Dom.',
        street: '',
        city: '',
        state: '',
        zipCode: '',
        notes: '',
        avatar: '/static/images/avatars/avatar_1.png',
    },
    {
        id: 2,
        firstName: 'Tomas',
        lastName: '',
        jobTitle: 'Dir. Comercial',
        email: 'tomas@gmail.com',
        workPhone: '2829',
        homePhone: '',
        mobilePhone: '',
        country: 'EE. UU.',
        street: '',
        city: '',
        state: '',
        zipCode: '',
        notes: '',
        avatar: '/static/images/avatars/avatar_3.png',
    },
]